// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package yrv_mcu_passthrough_pkg;

    localparam YRV_MCU_PASSTHROUGH_DATA_WIDTH = 32;
    localparam YRV_MCU_PASSTHROUGH_MIN_ADDR_WIDTH = 3;
    localparam YRV_MCU_PASSTHROUGH_SIZE = 'h4;

    typedef struct {
        logic [7:0] value;
    } yrv_mcu_passthrough__YRV_MCU_LED_CTRL__CTRL__out_t;

    typedef struct {
        yrv_mcu_passthrough__YRV_MCU_LED_CTRL__CTRL__out_t CTRL;
    } yrv_mcu_passthrough__YRV_MCU_LED_CTRL__out_t;

    typedef struct {
        yrv_mcu_passthrough__YRV_MCU_LED_CTRL__out_t YRV_MCU_LED_CTRL;
    } yrv_mcu_passthrough__out_t;
endpackage
