#ifndef RISC_V_CPU_CONFIG_H
#define RISC_V_CPU_CONFIG_H

   #define USE_EXTERNAL_INTERRUPT_AS_TIMER_INTERRUPT
// #define USE_YRV_PLATFORM_LOCAL_INTERRUPT_2_AS_TIMER_INTERRUPT

#endif  // ifndef RISC_V_CPU_CONFIG_H
