#ifndef RISC_V_CPU_CONFIG_H
#define RISC_V_CPU_CONFIG_H

#define RISC_V_CORE_APS       1
#define RISC_V_CORE_YRV       2
#define RISC_V_CORE_PICORV32  3

#define RISC_V_CORE RISC_V_CORE_APS

#define TIMER_INTERRUPT_USE_EXTERNAL_INTERRUPT              1
#define TIMER_INTERRUPT_USE_YRV_PLATFORM_LOCAL_INTERRUPT_2  2

#define TIMER_INTERRUPT TIMER_INTERRUPT_USE_YRV_PLATFORM_LOCAL_INTERRUPT_2

#endif  // ifndef RISC_V_CPU_CONFIG_H
