// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef YRV_MCU_PASSTHROUGH_H
#define YRV_MCU_PASSTHROUGH_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - yrv_mcu_passthrough::YRV_MCU_LED_CTRL
#define YRV_MCU_PASSTHROUGH__YRV_MCU_LED_CTRL__CTRL_bm 0xff
#define YRV_MCU_PASSTHROUGH__YRV_MCU_LED_CTRL__CTRL_bp 0
#define YRV_MCU_PASSTHROUGH__YRV_MCU_LED_CTRL__CTRL_bw 8
#define YRV_MCU_PASSTHROUGH__YRV_MCU_LED_CTRL__CTRL_reset 0x0

// addrmap - yrv_mcu_passthrough
typedef struct __attribute__ ((__packed__)) {
    uint32_t YRV_MCU_LED_CTRL;
} yrv_mcu_passthrough_t;


static_assert(sizeof(yrv_mcu_passthrough_t) == 0x4, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* YRV_MCU_PASSTHROUGH_H */
