#ifndef RISCV_CPU_CONFIG_H
#define RISCV_CPU_CONFIG_H

// #define USE_EXTERNAL_INTERRUPT_AS_TIMER_INTERRUPT
   #define USE_YRV_PLATFORM_LOCAL_INTERRUPT_2_AS_TIMER_INTERRUPT

#endif  // ifndef RISCV_CPU_CONFIG_H
