`include "lab_specific_board_config.svh"

`include "pkg/alu_opcodes_pkg.sv"
`include "pkg/csr_pkg.sv"
`include "pkg/decoder_pkg.sv"
`include "pkg/memory_pkg.sv"
`include "pkg/vgachargen_pkg.sv"
`include "pkg/peripheral_pkg.sv"
`include "pkg/bluster_pkg.sv"
`include "pkg/jtag_pkg.sv"
`include "pkg/platform_pkg.sv"

`include "aps_cpu/debouncer.sv"

`include "peripheral_modules/hex_digits.sv"
`include "peripheral_modules/PS2Receiver.sv"
`include "peripheral_modules/uart_rx.sv"
`include "peripheral_modules/uart_tx.sv"
`include "peripheral_modules/vgachargen.sv"

`include "sys_bus_controllers/hex_sb_ctrl.sv"
`include "sys_bus_controllers/led_sb_ctrl.sv"
`include "sys_bus_controllers/ps2_sb_ctrl.sv"
`include "sys_bus_controllers/sw_sb_ctrl.sv"
`include "sys_bus_controllers/timer.sv"
`include "sys_bus_controllers/uart_rx_sb_ctrl.sv"
`include "sys_bus_controllers/uart_tx_sb_ctrl.sv"
`include "sys_bus_controllers/vga_sb_ctrl.sv"

`include "aps_cpu/alu.sv"
`include "aps_cpu/bluster.sv"
`include "aps_cpu/cdc_pulse_sync.sv"
`include "aps_cpu/clock_divider.sv"
`include "aps_cpu/csr_controller.sv"
`include "aps_cpu/daisy_chain.sv"
`include "aps_cpu/data_mem.sv"
`include "aps_cpu/decoder.sv"
`include "aps_cpu/interrupt_controller.sv"
`include "aps_cpu/jtag_debug.sv"
`include "aps_cpu/lsu.sv"
`include "aps_cpu/register_file.sv"
`include "aps_cpu/rw_instr_mem.sv"
`include "aps_cpu/processor_core.sv"
`include "aps_cpu/processor_system.sv"