#ifndef RISCV_CPU_CONFIG_H
#define RISCV_CPU_CONFIG_H

#define RISCV_CORE_APS       1
#define RISCV_CORE_YRV       2
#define RISCV_CORE_PICORV32  3

#define RISCV_CORE RISCV_CORE_APS

#define TIMER_INTERRUPT_USE_EXTERNAL_INTERRUPT              1
#define TIMER_INTERRUPT_USE_YRV_PLATFORM_LOCAL_INTERRUPT_2  2

#define TIMER_INTERRUPT TIMER_INTERRUPT_USE_YRV_PLATFORM_LOCAL_INTERRUPT_2

#endif  // ifndef RISCV_CPU_CONFIG_H
