#define APS_PLATFORM_TIMER_BASE_ADDR                    0x08000000

#define APS_PLATFORM_TIMER_SYS_COUNTER_LOW_BITS_OFFSET    0x00
#define APS_PLATFORM_TIMER_SYS_CCOUNTER_HIGH_BITS_OFFSET  0x04
#define APS_PLATFORM_TIMER_DELAY_LOW_BITS_OFFSET          0x08
#define APS_PLATFORM_TIMER_DELAY_HIGH_BITS_OFFSET         0x0C
#define APS_PLATFORM_TIMER_MODE_OFFSET                    0x10
#define APS_PLATFORM_TIMER_REPEAT_NUMBER_OFFSET           0x14
#define APS_PLATFORM_TIMER_SOFT_RESET_OFFSET              0x24

#define APS_PLATFORM_TIMER_SYS_COUNTER_LOW_BITS_ADDR    (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_SYS_COUNTER_LOW_BITS_OFFSET  )
#define APS_PLATFORM_TIMER_SYS_CCOUNTER_HIGH_BITS_ADDR  (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_SYS_CCOUNTER_HIGH_BITS_OFFSET)
#define APS_PLATFORM_TIMER_DELAY_LOW_BITS_ADDR          (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_DELAY_LOW_BITS_OFFSET        )
#define APS_PLATFORM_TIMER_DELAY_HIGH_BITS_ADDR         (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_DELAY_HIGH_BITS_OFFSET       )
#define APS_PLATFORM_TIMER_MODE_ADDR                    (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_MODE_OFFSET                  )
#define APS_PLATFORM_TIMER_REPEAT_NUMBER_ADDR           (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_REPEAT_NUMBER_OFFSET         )
#define APS_PLATFORM_TIMER_SOFT_RESET_ADDR              (APS_PLATFORM_TIMER_BASE_ADDR + APS_PLATFORM_TIMER_SOFT_RESET_OFFSET            )

#define APS_TIMER_MODE_OFF      0
#define APS_TIMER_MODE_NTIMES   1
#define APS_TIMER_MODE_FOREVER  2

#define APS_PLATFORM_SW_BASE_ADDR                   0x01000000
#define APS_PLATFORM_SW_VAL_OFFSET                  0x00

#define APS_PLATFORM_LED_BASE_ADDR                  0x02000000
#define APS_PLATFORM_LED_VAL_OFFSET                 0x00

#define APS_PLATFORM_PS2_BASE_ADDR                  0x03000000
#define APS_PLATFORM_PS2_SCANCODE_OFFSET            0x00
#define APS_PLATFORM_PS2_SCANCODE_IS_UNREAD_OFFSET  0x04

#define APS_PLATFORM_7SEG_BASE_ADDR                 0x03000000
#define APS_PLATFORM_7SEG_0_OFFSET                  0x00
#define APS_PLATFORM_7SEG_1_OFFSET                  0x04
#define APS_PLATFORM_7SEG_2_OFFSET                  0x08
#define APS_PLATFORM_7SEG_3_OFFSET                  0x0C
#define APS_PLATFORM_7SEG_4_OFFSET                  0x10
#define APS_PLATFORM_7SEG_5_OFFSET                  0x14
#define APS_PLATFORM_7SEG_6_OFFSET                  0x18
#define APS_PLATFORM_7SEG_7_OFFSET                  0x1C
#define APS_PLATFORM_7SEG_ON_MASK_OFFSET            0x20
